/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "slCommon.h"

//==============================================================================
/**
*/
class RP2A03AudioProcessorEditor  : public slAudioProcessorEditor
{
public:
    RP2A03AudioProcessorEditor (RP2A03AudioProcessor&);
    ~RP2A03AudioProcessorEditor();

    //==============================================================================
    void resized() override;
    void paint (Graphics& g) override;

    RP2A03AudioProcessor& processor;
    
    drow::TriggeredScope scope;
    Image logo;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (RP2A03AudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
